### PR TITLE
Setup for multiple functions in one lambda

### PR DESCRIPTION
**Pull request by zaro0508**
Setup repo to build lambda with multiple functions.
The only way to setup multiple functions in one lambda is to
move requirements.txt to the root and specify the src folder in
the CFN Handler parameter instead of CodeUri parameter.

### CODE REVIEW

**Comment by cascadianblue** [comment]
This seems out of line with my reading of Amazon's prescribed [best practices for lambdas](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html), which seems to conceptually consider 1 Lambda = 1 Function.

I looked for other workarounds for packaging more functionality into 1 lambda:

- [this one](https://stackoverflow.com/a/50688766/2437926), which advocates adding a field to the incoming `Event`. Would that be doable?

**Review by cascadianblue — COMMENTED** [review]
see [my other comment](https://github.com/Sage-Bionetworks-IT/lambda-template/pull/19#issuecomment-697000707)

**Review by brucehoff — APPROVED** [review]
Nice!

**Comment by zaro0508** [comment]
> This seems out of line with my reading of Amazon's prescribed [best practices for lambdas](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html), which seems to conceptually consider 1 Lambda = 1 Function.

Could you point me to what you think suggests `1 Lambda = 1 Function`?   I don't see anything like that in the doc.  

> I looked for other workarounds for packaging more functionality into 1 lambda:
> * [this one](https://stackoverflow.com/a/50688766/2437926), which advocates adding a field to the incoming `Event`. Would that be doable?

This is not a workaround, this is how the AWS lambda feature is designed.

**Comment by brucehoff** [comment]
> > This seems out of line with my reading of Amazon's prescribed [best practices for lambdas](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html), which seems to conceptually consider 1 Lambda = 1 Function.
> 
> Could you point me to what you think suggests `1 Lambda = 1 Function`? I don't see anything like that in the doc.
> 
> > I looked for other workarounds for packaging more functionality into 1 lambda:
> > 
> > * [this one](https://stackoverflow.com/a/50688766/2437926), which advocates adding a field to the incoming `Event`. Would that be doable?
> 
> This is not a workaround, this is how the AWS lambda feature is designed.

This is really interesting.  Taking `fn-cr-synapse-tagger` as an example, I see that it is a custom resource which is itself a collection of resources.  Two of those resources are functions. So when you create a synapse-tagger resource it would appear that both functions are called.  Is that correct, or is just one called and, if so, how does the stack referencing the resource indicate which to call?

**Comment by zaro0508** [comment]
> So when you create a synapse-tagger resource it would appear that both functions are called. Is that correct, or is just one called and, if so, how does the stack referencing the resource indicate which to call?

No, only one function is called.  The lambda function that is called is referenced by the custom resource "ServiceToken" parameter.  Take a look at the usage section in the synapse-tagger readme: https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger#use-in-a-cloudformation-template

**Comment by brucehoff** [comment]
> > So when you create a synapse-tagger resource it would appear that both functions are called. Is that correct, or is just one called and, if so, how does the stack referencing the resource indicate which to call?
> 
> No, only one function is called. The lambda function that is called is referenced by the custom resource "ServiceToken" parameter. Take a look at the usage section in the synapse-tagger readme: https://github.com/Sage-Bionetworks-IT/cfn-cr-synapse-tagger#use-in-a-cloudformation-template

I see, thanks.  So the pattern is that 1 repo = 1 custom resource, but that 1 custom resource can actually be a 'library' of related resources that perhaps do slightly different things, and the stack which includes the custom resource can select the behavior that it invokes.  It seems like it's a matter of judgment as to whether the individual functions are similar enough to group into a custom resource (like the bucket tagger and the instance tagger) or so different that they should each be in their own repo.

**Review by cascadianblue — APPROVED** [review]

**Comment by zaro0508** [comment]
> I see, thanks. So the pattern is that 1 repo = 1 custom resource, but that 1 custom resource can actually be a 'library' of related resources that perhaps do slightly different things, and the stack which includes the custom resource can select the behavior that it invokes. It seems like it's a matter of judgment as to whether the individual functions are similar enough to group into a custom resource (like the bucket tagger and the instance tagger) or so different that they should each be in their own repo.

yes, exactly @brucehoff.  that's why i thought your `Sage-Bionetworks-IT/lambda-send-budget-alert` could just live with `Sage-Bionetworks-IT/lambda-budgets`

**Pull request merged**
